### ISSUE TITLE
Improve code style

### ISSUE THREAD

**Issue by kirmar** [alestic/email-bloom#1]
Would you be interested in reviewing a PR with changes that conform to PEP 8?

I have an update for indentation and your variable name "file".

**Comment by ehammond** [comment]
kirmar:

Thanks for offering. I would certainly take a look at your suggestions. I dabble in Python, but focus more on getting things to work than style, where I'm sure I have a lot to learn.

**Comment by ehammond** [comment]
Resolved with PR#1.

Thanks, kirmar!

**Comment by ehammond** [comment]
Er, make that PR #2
